[PDF]
qbroad = 5.23424363e-03
qdamp = 8.11835597e-03

[Measurement]
keV = 22.14
[R_val]
rmin = 0
rmax = 20
rstep = 0.01
[files]
cifs = './cifs/'
out = './results/'
[Verbose]
step = true
results = true

[Restraints]
delta2 = [0.0, 8.0, 1.0]
scale = [0.0, 1.0, 0.1]
adp = [0.0, 8.0]
cfs = [0.0, 400.0, 200.0]
occ = [0.0, 1.0, 1.0]
lat = 0.9


[[param_order]]
free = ["lat", "scale"]
fix = []

[[param_order]]
free = ["cfs"]
fix = []

[[param_order]]
free = ["delta2", "adp"] 
fix = []

